name: push docker-image to dockerhub and github

on:
  push:
    #tags:
     # - v*
jobs:
  build_image_job:
    runs-on: ubuntu-latest
    name: Build Docker Image
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_TOKEN }}


      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            lukyanchyk/docker_build
            ghcr.io/${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      - name: slack Notification
        uses: rtCamp/action-slack-notify@v2 
        env:
          SLACK_CHANNEL: github_notifications
          SLACK_TITLE: 'PUSH IMAGE'
          SLACK_COLOR: ${{ job.status }}
          LACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: |
            'Images have been pushed to registry.'
            'IMAGE: ${{ github.repository }} version ${{ github.run_number }}'
          SLACK_USERNAME: GitHub
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
