name:  Kyber minikube and KinD


on:
  - push
  - pull_request
          
jobs:
  job1:
    env:
      result_file: result.log
    runs-on: ubuntu-latest
    name: job1
    steps:
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      # now you can run kubectl to see the pods in the cluster
      - name: Info
        run: |
          echo "info<<EOF" >> ${{ env.result_file }}
          kubectl get node >> ${{ env.result_file }}
          kubectl version --short >> ${{ env.result_file }}

      - name: Upload file to slack 
      uses: adrey/slack-file-upload-action@master
      with:
        token: ${{ secrets.SLACK_WEBHOOK }}
        path: ${{ env.result_file }}
        channel: monitoring
