name:  Kyber minikube and KinD


on:
  - push
  - pull_request
          
jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      # now you can run kubectl to see the pods in the cluster
      - name: kubectl node
        run: kubectl get node
      - name : kubectl version
        run: kubectl get version
      - name: Time to up minikube
