name: create image to test_kuber
on:
  workflow_dispatch
jobs:
  build_image_job:
    runs-on: ubuntu-latest
    name: Build Docker Image
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./test_kuber
          push: true
          tags: test
          labels: ghcr.io/lukyanchyk/test
